# Spring MVC dispatcher servlet path for Actuator endpoints
server:  
  servlet:
    contextPath: /knowledge
  port: 8081
spring:
  application:
    name: knowledge-service
  jpa:
    show-sql: true
    hibernate:
#      ddl-auto: create-drop
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost/knowledge?useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
      
